import { Hero } from './hero';
  
export const HEROS: Hero[] = [
    {
        id: 1,
        name: "Arkan",
        hp: 100,
        attaqueSpeciale: 8,
        picture: "../assets/21474462.jpg",
        type: "feu",
    },
    {
        id: 2,
        name: "Lyra",
        hp: 120,
        attaqueSpeciale: 6,
        picture: "../assets/21474462.jpg",
        type: "eau",
    },
    {
        id: 3,
        name: "Aiden",
        hp: 80,
        attaqueSpeciale: 12,
        picture: "../assets/21474462.jpg",
        type: "feu",
    },
    {
        id: 4,
        name: "Elara",
        hp: 150,
        attaqueSpeciale: 1,
        picture: "../assets/21474462.jpg",
        type: "eau",
    },
    {
        id: 5,
        name: "Magnus",
        hp: 110,
        attaqueSpeciale: 9,
        picture: "../assets/21474462.jpg",
        type: "feu",
    },
    {
        id: 6,
        name: "Seraphina",
        hp: 110,
        attaqueSpeciale: 9,
        picture: "../assets/21474462.jpg",
        type: "plante",
    },
    {
        id: 7,
        name: "Draven",
        hp: 130,
        attaqueSpeciale: 6,
        picture: "../assets/21474462.jpg",
        type: "feu",
    },
    {
        id: 8,
        name: "Freya",
        hp: 70,
        attaqueSpeciale: 14,
        picture: "../assets/21474462.jpg",
        type: "plante",
    },
    {
        id: 9,
        name: "Orion",
        hp: 118,
        attaqueSpeciale: 6,
        picture: "../assets/21474462.jpg",
        type: "plante",
    },
    {
        id: 10,
        name: "Lumiya",
        hp: 120,
        attaqueSpeciale: 5,
        picture: "../assets/21474462.jpg",
        type: "eau",
    },
    {
        id: 11,
        name: "Xander",
        hp: 100,
        attaqueSpeciale: 8,
        picture: "../assets/21474462.jpg",
        type: "plante",
    },
    {
        id: 12,
        name: "Nova",
        hp: 140,
        attaqueSpeciale: 2,
        picture: "../assets/21474462.jpg",
        type: "eau",
    }
];